name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /path/to/your-key-pair.pem ec2-user@your-ec2-instance-public-dns << 'EOF'
          cd /home/ec2-user/your-repository
          git pull origin main
          source venv/bin/activate
          sudo systemctl restart getwebhook.service
          EOF
